development:
  adapter: postgresql
  database: ritly_review_development_live
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ritly_review_test_live
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ritly_review_prod_best_db_ever
  pool: 5
  timeout: 5000
